import * as fs from 'fs';
import * as path from 'path';
import type { MigrationReport } from '@transmuter/core-engine';

/**
 * Generate and write a markdown migration report.
 */
export function writeReport(report: MigrationReport, outputDir: string): string {
  const content = buildReport(report);
  const reportPath = path.join(outputDir, 'migration-report.md');
  fs.writeFileSync(reportPath, content, 'utf-8');
  return reportPath;
}

function buildReport(report: MigrationReport): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push('# Transmuter Migration Report');
  lines.push('');
  lines.push(`Generated: ${now}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Total classes found | ${report.totalClasses} |`);
  lines.push(`| Successfully converted | ${report.converted} |`);
  lines.push(`| Flagged for manual review | ${report.flagged} |`);
  lines.push(`| Skipped | ${report.skipped} |`);
  lines.push('');

  if (report.flaggedItems.length > 0) {
    lines.push('## Items Requiring Manual Review');
    lines.push('');
    lines.push('These classes could not be fully converted automatically:');
    lines.push('');
    for (const item of report.flaggedItems) {
      lines.push(`### \`${item.className}\``);
      lines.push('');
      lines.push(`**Reason:** ${item.reason}`);
      lines.push('');
    }
  }

  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Review flagged items above and complete manual migration');
  lines.push('2. Run `npx prisma migrate dev` to apply database migrations');
  lines.push('3. Update imports in converted files as needed');
  lines.push('4. Add business logic to generated service stubs');
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [Transmuter.ai](https://github.com/transmuter-ai)*');

  return lines.join('\n');
}
