import type { ParseResult, ProjectParseResponse, PrismaRelationDirective } from './types';
import { javaToPrisma } from './type-map';

const PRISMA_HEADER = `// This file was generated by Transmuter.ai
// Edit with care — re-running transmuter migrate will overwrite this file.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

// ─────────── Public API ───────────

/** Generate a single Prisma model block. Used by /convert/simple (backward compat). */
export function generatePrismaModel(entity: ParseResult): string {
  return renderEntityModel(entity, []);
}

/**
 * Generate a complete schema.prisma from a full project parse response.
 * Includes datasource, generator, enums, and all entity models with relations.
 */
export function generatePrismaSchema(
  response: ProjectParseResponse,
  directives: PrismaRelationDirective[],
): string {
  const parts: string[] = [PRISMA_HEADER];

  // Build set of known enum type names for field type resolution
  const knownEnums = new Set(response.enums.map((e) => e.className));

  // Enums
  for (const enumResult of response.enums) {
    parts.push(renderPrismaEnum(enumResult));
    parts.push('');
  }

  // Entity models (skip non-entities and @MappedSuperclass — their fields are inlined)
  const entities = response.classes.filter(
    (c) => (c.isEntity || c.stereotype === 'entity') && !c.isMappedSuperclass,
  );
  for (const entity of entities) {
    const entityDirectives = directives.filter(
      (d) => d.ownerClass === entity.className || d.targetClass === entity.className,
    );
    parts.push(renderEntityModel(entity, entityDirectives, knownEnums));
    parts.push('');
  }

  return parts.join('\n').trimEnd() + '\n';
}

// ─────────── Renderers ───────────

function renderPrismaEnum(enumResult: ParseResult): string {
  const lines: string[] = [`enum ${enumResult.className} {`];
  for (const val of enumResult.enumValues ?? []) {
    lines.push(`  ${val.name}`);
  }
  lines.push('}');
  return lines.join('\n');
}

function renderEntityModel(
  entity: ParseResult,
  directives: PrismaRelationDirective[],
  knownEnums: Set<string> = new Set(),
): string {
  const lines: string[] = [];

  lines.push(`model ${entity.className} {`);

  // Build all fields to render (scalars + synthesized FKs + relation objects)
  const fieldRows = buildFieldRows(entity, directives, knownEnums);

  // Calculate column widths for alignment
  const maxName = Math.max(...fieldRows.map((r) => r.name.length), 1);
  const maxType = Math.max(...fieldRows.map((r) => r.type.length), 1);

  for (const row of fieldRows) {
    const namePad = ' '.repeat(maxName - row.name.length + 1);
    const typePad = ' '.repeat(maxType - row.type.length + 1);
    const decorStr = row.decorators.length > 0 ? typePad + row.decorators.join(' ') : '';
    lines.push(`  ${row.name}${namePad}${row.type}${decorStr}`);
  }

  if (entity.tableName) {
    lines.push('');
    lines.push(`  @@map("${entity.tableName}")`);
  }

  lines.push('}');
  return lines.join('\n');
}

interface FieldRow {
  name: string;
  type: string;
  decorators: string[];
}

function buildFieldRows(
  entity: ParseResult,
  directives: PrismaRelationDirective[],
  knownEnums: Set<string> = new Set(),
): FieldRow[] {
  const rows: FieldRow[] = [];

  // Track which synthetic FK fields we've already added
  const addedFkFields = new Set<string>();

  for (const field of entity.fields) {
    // Skip @Transient fields
    if (field.isTransient) continue;

    // Skip relation fields — they will be rendered separately below
    if (field.relation) continue;

    // If the field type is a known enum, use it directly in Prisma
    const prismaType = knownEnums.has(field.type)
      ? field.type
      : (javaToPrisma[field.type] ?? 'String');
    const isId = field.annotations.includes('Id');
    const isGenerated = field.annotations.includes('GeneratedValue');
    const nullable = field.nullable && !isId;

    const typeStr = prismaType + (nullable ? '?' : '');
    const decorators: string[] = [];
    if (isId) decorators.push('@id');
    if (isGenerated) decorators.push('@default(autoincrement())');

    rows.push({ name: field.name, type: typeStr, decorators });
  }

  // Relation-derived fields for directives where this class is the OWNER
  const ownerDirectives = directives.filter((d) => d.ownerClass === entity.className);
  for (const d of ownerDirectives) {
    if (d.relationType === 'ManyToMany') {
      // Implicit many-to-many: just add the array relation field; Prisma manages the join table
      rows.push({
        name: findRelationFieldName(entity, d.targetClass) ?? d.ownerField,
        type: `${d.targetClass}[]`,
        decorators: [],
      });
    } else {
      // ManyToOne / OneToOne owning side: add FK scalar + relation object field
      if (!addedFkFields.has(d.foreignKeyField)) {
        rows.push({ name: d.foreignKeyField, type: 'Int', decorators: [] });
        addedFkFields.add(d.foreignKeyField);
      }
      const fieldName = findRelationFieldName(entity, d.targetClass) ?? d.ownerField;
      rows.push({
        name: fieldName,
        type: d.targetClass,
        decorators: [
          `@relation(fields: [${d.foreignKeyField}], references: [id])`,
        ],
      });
    }
  }

  // Relation-derived fields for directives where this class is the TARGET (inverse side)
  const targetDirectives = directives.filter((d) => d.targetClass === entity.className);
  for (const d of targetDirectives) {
    if (d.relationType === 'ManyToOne' || d.relationType === 'OneToOne') {
      // Inverse of ManyToOne: add the array/object field on the "one" side
      const fieldName = findRelationFieldNameOnTarget(entity, d.ownerClass) ?? lcFirst(d.ownerClass) + 's';
      rows.push({ name: fieldName, type: `${d.ownerClass}[]`, decorators: [] });
    }
    if (d.relationType === 'ManyToMany') {
      // Inverse of ManyToMany: add the array field
      const fieldName = findRelationFieldNameOnTarget(entity, d.ownerClass) ?? lcFirst(d.ownerClass) + 's';
      rows.push({ name: fieldName, type: `${d.ownerClass}[]`, decorators: [] });
    }
  }

  return rows;
}

// Find the field name on `entity` that references `targetClass`
function findRelationFieldName(entity: ParseResult, targetClass: string): string | undefined {
  return entity.fields.find(
    (f) => f.relation?.targetClass === targetClass,
  )?.name;
}

// Find the field name on `entity` that references `ownerClass` from the inverse side
function findRelationFieldNameOnTarget(entity: ParseResult, ownerClass: string): string | undefined {
  return entity.fields.find(
    (f) => f.relation?.targetClass === ownerClass,
  )?.name;
}

function lcFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}
